### PR TITLE
Add support for Google Analytics

### PR DESCRIPTION
**Pull request by FraBle**

### CODE REVIEW

**Comment by ojroques** [comment]
Thanks for the PR ! It's merged.

**Comment by somnathrakshit** [comment]
Can you please add this to the example site? I am not sure how to enable this on my site.

**Comment by ojroques** [comment]
Here's how to configure Google Analytics: https://gohugo.io/templates/internal/#google-analytics.
 You should add your tracking id to your config file and it will be enabled. I've also updated the example site [config](https://github.com/ojroques/hugo-researcher/blob/master/exampleSite/config.toml).

**Comment by somnathrakshit** [comment]
Thank you!

**Pull request merged**
